language: node_js
node_js:
  - 8
env:
  - NODE_ENV=test CXX="g++-4.8" CC="gcc-4.8"
services:
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
    - clang
before_install:
  - sudo chmod -R 777 /var/cache/debconf
  - sudo echo arangodb3 arangodb3/password password somepwd | debconf-set-selections
  - sudo echo arangodb3 arangodb3/password_again password somepwd | debconf-set-selections
  - curl -O https://download.arangodb.com/arangodb32/xUbuntu_14.04/Release.key
  - sudo apt-key add - < Release.key
  - echo 'deb https://download.arangodb.com/arangodb32/xUbuntu_14.04/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
  - sudo apt-get install arangodb3=3.2.6
before_script:
  - cp ./config/secret/sample.js ./config/secret/test.js
  - npm run init-db-standalone
  - npm run init
script:
  - npm run lint
  - npm test
